### ISSUE TITLE
疑问、BUG

### ISSUE THREAD

**Issue by lcysgsg** [FontEndArt/uni-circle#1]
`<view v-if="!this.BgId && !this.InId">` （没懂这个判断是什么意思）
你的demo自己跑过多端吗？
语法错了， 不能用this的
小程序里能跑应该是语法错了直接排除了， web端解析的应该是false， 所以现在有一个小程序与web端表现不一的情况

**Comment by FontEndArt** [comment]
不好意思哈  没有跑过多端   仅在app端使用    我发布的这个插件只是从我项目中摘出来的小功能   我一会把插件备注改为app端用

**Comment by lcysgsg** [comment]
@FontEndArt  看下重点... 语法错了， 这里的这个 if 根本就没起作用， 不管是哪个端的，语法还是基于 vue 。 app端能跑只是恰好能跑
